### PR TITLE
Make Tuple parametrized with generic so it can be used for granular c…

### PR DESCRIPTION
**Pull request by Andarist**
…onditional checks

### CODE REVIEW

**Comment by Andarist** [comment]
After a though - I'm not sure if this works correctly. It has fixed one of my issues but not sure if for good reasons. Generics are hard 🙈

**Comment by krzkaczor** [comment]
@Andarist Did you confirm that it works correctly? Tmrw I will conduct some tests on my own.

**Comment by Andarist** [comment]
I think it does, gonna try to write some test for this in a moment.

**Comment by Andarist** [comment]
Added test - it correctly restricts input tuples. It also accepts empty array though which is kinda a bummer.

**Comment by krzkaczor** [comment]
@Andarist ok cool, thanks! One last thing: could leave a note about parameters in readme?

**Comment by Andarist** [comment]
Done

**Comment by krzkaczor** [comment]
@Andarist thanks! 👍

**Pull request merged**
