### PR TITLE
A complete refactor to Deep* types

### PR DESCRIPTION
**Pull request by lucifer1004**
- Refactor DeepReadonly, DeepWritable, DeepPartial
- Implement DeepNonNullably
- Refactor and add related tests

This refactor should solve #14 #40 
And since all Deep types are very similar now, it provides a foundation for #12

### CODE REVIEW

**Comment by lucifer1004** [comment]
VS Code yields no errors, however, tsc fails.

**Comment by lucifer1004** [comment]
It is related to prettier... If I do not format the code, tsc can pass.

**Comment by lucifer1004** [comment]
TypeScript > 3.5 is OK, but 3.2 fails.

**Comment by lucifer1004** [comment]
I suggest we follow TypeScript > 3.5, in which arrays do not need specific judgment, and can be treated just like {}

**Comment by lucifer1004** [comment]
By treating arrays just like {}, issues with tuples (#40) are also addressed like charm.

**Comment by lucifer1004** [comment]
I realized that the easiest way is to upgrade TypeScript version in devDeps. So it's up to @krzkaczor to decide whether it is time to perform the upgrade.

**Comment by krzkaczor** [comment]
This is a really enormous help for the project! Thanks for this PR!

Bumping TS version is for sure not perfect but on the other hand, we can release this as version `ts-essentials@3.0.0` and let folks know that they can still use 2.x.x if they use older TS version.

I will need a while to review this PR. Hopefully today/tmrw I will get right back to you.

**Comment by krzkaczor** [comment]
Thanks! I am gonna merge this 🎉 

I created a new branch `next` and that is the branch for explicit support for TS 3.5. I will also publish it as `ts-essentials@3.0.0-beta.1` so it's already usable for early adopters. My plan would be to wait a little bit before releasing it to master to give the community time to migrate to TS 3.5. On `next` branch we can also remove deprecated types that became part of TS standard lib (`omit`)

**Comment by krzkaczor** [comment]
Part of `next` branch. Released as `ts-essentials@3.0.0-beta.0`

**Pull request merged**
