### PR TITLE
feat: Deep-* support for WeakMap/WeakSet/Promise/Error/RegExp

### PR DESCRIPTION
**Pull request by lucifer1004**
See #111 #113

### CODE REVIEW

**Comment by quezak** [comment]
Looks good -- though I don't like the fact that the `Deep*` types have over 9000 cases each, it's probably inevitable if we want them to be truly universal.

**Comment by quezak** [comment]
One question though: is treating `Error` as a builtin type a good idea? One could have a custom error with custom object properties, and still want to have a `DeepPartial` of that.

**Comment by lucifer1004** [comment]
> Looks good -- though I don't like the fact that the `Deep*` types have over 9000 cases each, it's probably inevitable if we want them to be truly universal.

Yes... We really need a generic Deep type, but it still seems impossible right now, unless we have something like generic-generic types.

**Comment by lucifer1004** [comment]
> One question though: is treating `Error` as a builtin type a good idea? One could have a custom error with custom object properties, and still want to have a `DeepPartial` of that.

Actually similar things can also happen to other types. Users might extend a JS type and add some custom properties, but we cannot distinguish the modified versions from the raw ones using something like <T extends Error>.

**Comment by quezak** [comment]
> Actually similar things can also happen to other types. Users might extend a JS type and add some custom properties, but we cannot distinguish the modified versions from the raw ones using something like .

Yes, but I see no rational cases to have a partial of a `Function`, `RegExp` or `Date`, and surely all the primitives, while for `Error` it might actually make sense. @krzkaczor what do you think?

**Comment by krzkaczor** [comment]
I don't think that `Error` subtyping edge case is something we should worry about now. Thanks for your contribution!

**Pull request merged**
