### PR TITLE
test: improve testDeepWritableReverseIsDeepReadonlyForTotallyWritableType

### PR DESCRIPTION
**Pull request by yxliang01**
An improvement related to PR https://github.com/krzkaczor/ts-essentials/pull/33 . Add checks whether a `TotallyWritableType` is unchanged by `DeepWritable`.

### CODE REVIEW

**Comment by yxliang01** [comment]
Hmm the CI reports formatting problem. But, I don't know where the path shown is at.

**Comment by krzkaczor** [comment]
woah that's weird CI problem. Did you run `yarn test:fix`?

**Comment by yxliang01** [comment]
Yay! Finally passing. But, the path was really weird.

**Comment by krzkaczor** [comment]
Thanks! 👍

**Pull request merged**
